services:
  db:
    image: postgres:17
    volumes:
      - lastnight-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:8.4
    env_file:
      - .env
    volumes:
      - lastnight-pgadmin:/var/lib/pgadmin
    ports:
      - "4001:80"
    depends_on:
      - db

volumes:
  lastnight-db:
  lastnight-pgadmin:
